/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApiRouteImport } from './routes/api'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HrRouteImport } from './routes/hr'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/ai-copilot'
    | '/analytics'
    | '/api'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/data-sources'
    | '/documents'
    | '/finance'
    | '/forgot-password'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/marketing'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/ai-copilot'
    | '/analytics'
    | '/api'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/data-sources'
    | '/documents'
    | '/finance'
    | '/forgot-password'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/marketing'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-chat'
    | '/ai-copilot'
    | '/analytics'
    | '/api'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/data-sources'
    | '/documents'
    | '/finance'
    | '/forgot-password'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/marketing'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiChatRoute: typeof AiChatRoute
  AiCopilotRoute: typeof AiCopilotRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiRoute: typeof ApiRoute
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DocumentsRoute: typeof DocumentsRoute
  FinanceRoute: typeof FinanceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HrRoute: typeof HrRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiChatRoute: AiChatRoute,
  AiCopilotRoute: AiCopilotRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiRoute: ApiRoute,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  DocumentsRoute: DocumentsRoute,
  FinanceRoute: FinanceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HrRoute: HrRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
